version: 1.3.{build}

configuration: Release

platform: Any CPU

image: Visual Studio 2019 Preview

install:
  - cmd: choco install dotnetcore-sdk --pre

before_build:

- cmd: nuget restore source\MRU.sln

build:

  verbosity: minimal

artifacts:

- path: source\MRUDemo\bin\Release
  name: MRUDemo

- path: source\MRULib\bin\Release
  name: MRULib
